apiVersion: apps/v1                                                                                                         
kind: Deployment                                                                                                            
metadata:                                                                                                                   
  name: uptime-kuma                                                                                                         
  namespace: uptime-kuma                    
spec:                                   
  replicas: 1
  selector:                                                                                                                 
    matchLabels:
      app: uptime-kuma                                                                                                      
  template:     
    metadata:
      labels:
        app: uptime-kuma
    spec:
      nodeSelector:                         
        kubernetes.io/hostname: services-03
      containers:
        - name: uptime-kuma                                                                                                 
          image: louislam/uptime-kuma:2
          ports:                                                                                                            
            - containerPort: 3001       
          volumeMounts:
            - name: data                                                                                                    
              mountPath: /app/data
      volumes:                                                                                                              
        - name: data
          persistentVolumeClaim:
            claimName: uptime-kuma-data